version: '3'
services:
  bksy-feed:
    image: bsky:latest
    build:
      context: '.'
    volumes: 
      - /Users/jordanbyrd/bluesky/db.sql:/app/db.sql

    environment:
      - FEEDGEN_PORT=3000
      - FEEDGEN_LISTENHOST=0.0.0.0
      - FEEDGEN_SQLITE_LOCATION=db.sql
      - FEEDGEN_SUBSCRIPTION_ENDPOINT=wss://bsky.social
      # bsky.dev.host
      - FEEDGEN_HOSTNAME=localhost 
      - GOOG_API_KEY=${GOOG_API_KEY}
      - TARGET_SPREADSHEET_ID=${TARGET_SPREADSHEET_ID}
    ports:
      - 3000:3000